apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: kb8rzzy7n-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/kb8rzzy7n-java-springboot-gitops